### ISSUE TITLE
Package cant install, proposal for working preposed fix

### ISSUE THREAD

**Issue by wisehackermonkey** [crux/smoothed-z-score#4]
# Cant run package
![image](https://user-images.githubusercontent.com/29699356/145257374-0cdb56ce-7fd8-45ee-85aa-eaba1b35cd9b.png)

# Fix:
![image](https://user-images.githubusercontent.com/29699356/145257626-34fccd60-5d9a-40a6-9561-a1d01d94f829.png)
![image](https://user-images.githubusercontent.com/29699356/145257662-07e2e94b-1747-487a-8f90-e8c6fbdb2f2b.png)

# Works
![image](https://user-images.githubusercontent.com/29699356/145257752-ae2fbc2a-bf6f-4e0f-a533-af7c9ebd093a.png)

# from
package.json
```json
{
  ......
  "keywords": [],
  "type": "module",
  "scripts": {
   ......
}

```
# to
package.json
```json
{
  ......
  "keywords": [],

  "scripts": {
   ......
}

```

**Comment by crux** [comment]
awsome issue report! I could replicate and applied your fix. Uploaded and published as 0.1.2. Hope you had some use of it anyhow. For me that was a dead end, but I also used it to try with npm package publishing, check the node ecosphere a bit. Thanx a lot for your help! If you can make use of it, you can also take over the repo if you like.

**Comment by wisehackermonkey** [comment]
Thanks for responding! 
awesome id be down to take it over!

**Comment by wisehackermonkey** [comment]
how does that process work?

**Comment by crux** [comment]
I added you to the repo, github says you should get an invite. Once you have it, you can work/commit on the repo I guess. Don't know if this is the best way, but you should be able to commit/manage the repo as you like then.

**Comment by wisehackermonkey** [comment]
Hey thanks!

**Comment by wisehackermonkey** [comment]
Just accepted the invite
